<?php

?>

<h1>Crea una nova tasca</h1>

<form method="post">
  <label per="name">Nom de la Tasca:</label>
  <input type="text" id="name" name="name" required><br>

  <label per="username">Nom d'Usuari:</label>
  <input type="text" id="username" name="username" required><br>

  <label per="create_time">Data i hora de creació:</label>
  <input type="datetime-local" id="create_time" name="create_time" required><br>

  <label per="completed_time">Data i hora de finalització:</label>
  <input type="datetime-local" id="completed_time" name="completed_time" required><br>

  <input type="submit" value="Desar">
</form>
