<?php

$taskDetail = $this->taskDetail;
?>


<h1><?php echo $taskDetail->name ?></h1>

<p><?php echo $taskDetail->username ?></p>

<!-- Formulario para eliminar la tarea -->
<form method="post" onsubmit="return confirm('¿Estás seguro de que deseas eliminar esta tarea?');">
  <!-- Campo oculto para el ID de la tarea -->
  <input type="hidden" name="task_id" value="<?php echo htmlspecialchars($taskDetail->id, ENT_QUOTES, 'UTF-8'); ?>">

  <!-- Botón para enviar la solicitud POST -->
  <input type="submit" value="Eliminar Tasca" class="bg-red-500 text-white p-2 rounded">
</form>
