<?php

$allTasks = $this->allTasks;
?>

<div class="container mx-auto">
  <?php foreach ($allTasks as $task) : ?>
    <div class="bg-white shadow rounded-lg p-6 mb-4">
      <h2 class="text-xl font-semibold">Task ID: <?php echo $task->id; ?></h2>
      <p class="text-gray-700">
        <strong>Task Name:</strong> <?php echo $task->name; ?><br>
        <strong>Username:</strong> <?php echo $task->username; ?><br>
        <strong>Created Time:</strong> <?php echo $task->create_time; ?><br>
        <strong>Completed Time:</strong> <?php echo $task->completed_time ?? 'Not completed'; ?><br>
        <br />
        <br />
      </p>

      <!-- Formulario para borrar la tarea -->
      <form action="/task/destroy/<?php echo $task->id; ?>" method="post">
        <input type="hidden" name="task_id" value="<?php echo $task->id; ?>">
        <button type="submit" class="bg-red-500 text-white p-2 rounded">Eliminar Tasca</button>
      </form>

    </div>
  <?php endforeach; ?>
</div>
